# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/vgsys-root";
      fsType = "ext4";
    };

  fileSystems."/data" =
    { device = "/dev/mapper/vgsys-data";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/92C8-2F07";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # swap file (recommended for ssd-drives):
  swapDevices = [ {
    device = "/var/lib/swapfile";
    size = 32*1024;
    options = [ "discard" ]; # enable trim
    randomEncryption.enable = true; # generating a new key on each boot, makes hibernation impossible
  } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

}
